// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: userinfo.proto
#ifndef GRPC_userinfo_2eproto__INCLUDED
#define GRPC_userinfo_2eproto__INCLUDED

#include "userinfo.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace userinfo {

// The SendMessage service definition.
class SendMessage final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a user into
    virtual ::grpc::Status sendMessage(::grpc::ClientContext* context, const ::userinfo::UserRequest& request, ::userinfo::UserReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::UserReply>> AsyncsendMessage(::grpc::ClientContext* context, const ::userinfo::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::UserReply>>(AsyncsendMessageRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::userinfo::UserReply>* AsyncsendMessageRaw(::grpc::ClientContext* context, const ::userinfo::UserRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status sendMessage(::grpc::ClientContext* context, const ::userinfo::UserRequest& request, ::userinfo::UserReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::UserReply>> AsyncsendMessage(::grpc::ClientContext* context, const ::userinfo::UserRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::userinfo::UserReply>>(AsyncsendMessageRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::userinfo::UserReply>* AsyncsendMessageRaw(::grpc::ClientContext* context, const ::userinfo::UserRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::RpcMethod rpcmethod_sendMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a user into
    virtual ::grpc::Status sendMessage(::grpc::ServerContext* context, const ::userinfo::UserRequest* request, ::userinfo::UserReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_sendMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* context, const ::userinfo::UserRequest* request, ::userinfo::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendMessage(::grpc::ServerContext* context, ::userinfo::UserRequest* request, ::grpc::ServerAsyncResponseWriter< ::userinfo::UserReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sendMessage<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_sendMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* context, const ::userinfo::UserRequest* request, ::userinfo::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_sendMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::StreamedUnaryHandler< ::userinfo::UserRequest, ::userinfo::UserReply>(std::bind(&WithStreamedUnaryMethod_sendMessage<BaseClass>::StreamedsendMessage, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* context, const ::userinfo::UserRequest* request, ::userinfo::UserReply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::userinfo::UserRequest,::userinfo::UserReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_sendMessage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_sendMessage<Service > StreamedService;
};

}  // namespace userinfo


#endif  // GRPC_userinfo_2eproto__INCLUDED
